name: 'MLOps in Production'

on:
  push:
    branches:
      - 'main'

env:
  IMAGE_ML_APP: week_2

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: week_2/
          file: week_2/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_ML_APP}}:latest
          cache-from: type=registry,ref=dpekach/week_2:buildcache
          cache-to: type=registry,ref=dpekach/week_2:buildcache,mode=max

