name: 'MLOps in Production'

on:
  push:
    branches:
      - 'main'

env:
  IMAGE_ML_APP: week_3_tests


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: week_3_tests/
          file: week_3_tests/Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_MAIN_NAME }}:${{ env.IMAGE_MAIN_TAG }}
          cache-from: type=registry,ref=dpekach/week_3:buildcache
          cache-to: type=registry,ref=dpekach/week_3:buildcache,mode=max
      - name: Build new
        run: |
          docker build -f week_3_tests/Dockerfile -t nlp-sample:latest week-3_tests
      - name: Test code
        run: |
          docker run nlp-sample:latest make test_code
      - name: Test data
        run: |
          docker run nlp-sample:latest make test_data
      - name: Test model
        run: |
          docker run nlp-sample:latest make test_model
      - name: Push
        uses: docker/build-push-action@v2
        with:
          context: week_3_tests
          file: week_3_tests/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_MAIN_NAME }}:${{ env.IMAGE_MAIN_TAG }}
          cache-from: type=registry,ref=dpekach/week_3_tests:buildcache
          cache-to: type=registry,ref=dpekach/week_3_tests:buildcache,mode=max